name: "Motivation Bot"

on:
  issues:
    types: [labeled]

jobs:
  motivate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies for Motivate Action
        run: npm install
        working-directory: .github/actions/motivate-action

      - name: Run Motivate Action
        uses: ./.github/actions/motivate-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
